services:
  # PHP-FPM Service with Laravel
  jatlaravel_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        - USER_ID=${UID:-1000}
        - GROUP_ID=${GID:-1000}
    container_name: jatlaravel_app
    restart: unless-stopped
    working_dir: /var/www/jatlaravel
    volumes:
      - ./src:/var/www/jatlaravel:cached
      - jatlaravel_storage:/var/www/jatlaravel/storage
      - jatlaravel_cache:/var/www/jatlaravel/bootstrap/cache
    networks:
      - jatlaravel_network

  # Nginx Service
  jatlaravel_nginx:
    image: nginx:alpine
    container_name: jatlaravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/jatlaravel:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jatlaravel_app
    networks:
      - jatlaravel_network

  # MySQL Service
  jatlaravel_db:
    image: mysql:8.0
    container_name: jatlaravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3316:3306"
    volumes:
      - jatlaravel_dbdata:/var/lib/mysql
    networks:
      - jatlaravel_network

networks:
  jatlaravel_network:
    driver: bridge

volumes:
  jatlaravel_dbdata:
    driver: local
  jatlaravel_storage:
    driver: local
  jatlaravel_cache:
    driver: local